apiVersion: v1
kind: Service
metadata:
  name: springback-service
spec:
  type: NodePort
  selector:
    app: springback
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8085
      nodePort: 32256 
